---
title: "covid vaccine"
author: "Kevin Howlett"
date: "4/21/2021"
output: html_document
---



```{r warning=FALSE, message=FALSE}
library(tidyverse)

df <- read_csv('COVID-19_Vaccine_Distribution_Allocations_by_Jurisdiction_-_Pfizer.csv')

populations <- read_csv("/Users/kevinhowlett/Downloads/State Populations.csv")

counties <- read_csv('co-est2019-alldata.csv')

df$Code <- state.abb[match(df$Jurisdiction,state.name)]
df$Pop <- as.vector(populations[match(df$Jurisdiction, populations$State), 2]$`2018 Population`)
df$AllocationsPer1k <- df$`1st Dose Allocations`/df$Pop *1000

populations[populations$State == "Alaska",]


max(df$`AllocationsPer1k`, na.rm = T)


```

```{r}
library(plotly)

g <- list(
  scope = 'usa',
  projection = list(type = 'albers usa'),
  showlakes = TRUE,
  lakecolor = toRGB('white')
)

df2 <- df[df$`Week of Allocations`=="04/26/2021",]

fig <- plot_ly(data = df2, type="choropleth", locationmode = 'USA-states', 
               z = ~`AllocationsPer1k`, locations = ~Code,
               text = paste0("State: ", df2$Jurisdiction, "<br>",
                     "Population: ", round(df2$Pop/1000000, 2), "M<br>",
                     "Allocations per 1k: ", round(df2$`AllocationsPer1k`, 2), "<br>", "<br>"),
               hoverinfo = 'text', zmin = 0, zmax = 20) %>% layout(geo = g)
fig
```



```{r}
df <- read_csv('Vaccine_Hesitancy_for_COVID-19__County_and_local_estimates (1).csv')

df$fips <- as.character(df$`FIPS Code`)

df$fips <- ifelse(nchar(df$fips) < 5, paste0('0',df$fips), df$fips)

df %>% select(State, `County Name`, `FIPS Code`, fips, `Estimated hesitant`) %>%
  filter(State == 'CALIFORNIA')

```

```{r}
library(plotly)

url <- 'https://raw.githubusercontent.com/plotly/datasets/master/geojson-counties-fips.json'
counties <- rjson::fromJSON(file=url)

fig <- plot_ly() 
fig <- fig %>% add_trace(
    type="choroplethmapbox",
    geojson=counties,
    locations=df$fips,
    z=df$`Estimated hesitant`,
    colorscale="Viridis",
    marker=list(line=list(
      width=0),
      opacity=0.5
    )
  )

fig <- fig %>% layout(
    mapbox=list(
      style="carto-positron",
      zoom =2,
      center=list(lon= -95.71, lat=37.09))
  )

fig <- fig %>%
  add_trace(data = df,
          text = paste0("State: ", df$State, "<br>",
                     "County: ", df$`County Name`, "<br>",
                     "Proportion Hesitant: ", "<br>"),
          hoverinfo = 'text')

fig
```
